// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { getRequest } from '@tanstack/react-start/server'
import { createClient } from '@supabase/supabase-js'
import { Buffer } from 'node:buffer'
import type { Database } from './types'

function getTokenIssuer(token: string): string | null {
  try {
    const payload = token.split('.')[1];
    if (!payload) return null;
    const json = Buffer.from(payload.replace(/-/g, '+').replace(/_/g, '/'), 'base64').toString('utf8');
    const issuer = (JSON.parse(json) as { iss?: unknown }).iss;
    return typeof issuer === 'string' ? issuer : null;
  } catch {
    return null;
  }
}


export const requireSupabaseAuth = createMiddleware({ type: 'function' }).server(
  async ({ next }) => {
    
    const SUPABASE_URL = process.env.SUPABASE_URL;
    const SUPABASE_PUBLISHABLE_KEY = process.env.SUPABASE_PUBLISHABLE_KEY;

    if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
      const missing = [
        ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
        ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
      ];
      const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Connect Supabase in Lovable Cloud.`;
      console.error(`[Supabase] ${message}`);
      throw new Error(message);
    }
    
    const request = getRequest();

    if (!request?.headers) {
      throw new Error('Unauthorized: No request headers available');
    }

    const authHeader = request.headers.get('authorization');

    if (!authHeader) {
      throw new Error('Unauthorized: No authorization header provided');
    }

    if (!authHeader.startsWith('Bearer ')) {
      throw new Error('Unauthorized: Only Bearer tokens are supported');
    }

    const token = authHeader.replace('Bearer ', '');
    if (!token) {
      throw new Error('Unauthorized: No token provided');
    }

    const supabase = createClient<Database>(
      SUPABASE_URL!,
      SUPABASE_PUBLISHABLE_KEY!,
      {
        global: {
          headers: {
            Authorization: `Bearer ${token}`,
          },
        },
        auth: {
          storage: undefined,
          persistSession: false,
          autoRefreshToken: false,
        },
      }
    );

    // Validate against Supabase Auth itself instead of locally decoding the
    // token. This supports the current publishable-key format and prevents a
    // stale signing-key cache from rejecting a freshly-created account.
    const { data, error } = await supabase.auth.getUser(token);
    if (error || !data?.user) {
      const tokenIssuer = getTokenIssuer(token);
      const expectedIssuer = SUPABASE_URL.replace(/\/$/, '') + '/auth/v1';
      if (tokenIssuer && tokenIssuer !== expectedIssuer) {
        console.error('[Supabase] session/server project mismatch', { tokenIssuer, expectedIssuer });
        throw new Error(`Sua sessão pertence a ${tokenIssuer}, mas o servidor está configurado para ${SUPABASE_URL}. Na Vercel, deixe SUPABASE_URL e VITE_SUPABASE_URL iguais ao projeto da sua conta e faça um novo deploy.`);
      }
      console.error('[Supabase] session validation failed', { expectedIssuer, message: error?.message });
      throw new Error('Unauthorized: Invalid token');
    }

    return next({
      context: {
        supabase,
        userId: data.user.id,
        claims: data.user,
      },
    });
  },
);
